name: Quality
on: push
jobs:
    cs-fixer:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Cs-Fixer
                run: |
                    wget -q https://cs.symfony.com/download/php-cs-fixer-v3.phar -O php-cs-fixer
                    chmod a+x php-cs-fixer
                    PHP_CS_FIXER_IGNORE_ENV=true ./php-cs-fixer fix --dry-run --config=.php-cs-fixer.dist.php

    phpunit:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.2'
                    tools: composer:v2
                    coverage: pcov
            -   uses: actions/cache@v2
                with:
                    path: '**/vendor'
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-
            -   uses: php-actions/composer@v5
                with:
                    args: --prefer-dist
                    php_version: 8.2

            -   name: Run tests & generate Coverage
                run: bin/phpunit --configuration=phpunit.xml tests --coverage-html var/coverage --whitelist=src

            -   name: Store coverage files
                uses: actions/upload-artifact@v2
                with:
                    path: var/coverage

    phpstan:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/cache@v2
                with:
                    path: '**/vendor'
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-
            -   uses: php-actions/composer@v5
                with:
                    args: --prefer-dist
                    php_version: 8.2

            -   name: PHPStan
                uses: php-actions/phpstan@v2
                with:
                    path: src/
                    args: --level=4

    phpstan5:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/cache@v2
                with:
                    path: '**/vendor'
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-
            -   uses: php-actions/composer@v5
                with:
                    args: --prefer-dist
                    php_version: 8.2

            -   name: PHPStan
                uses: php-actions/phpstan@v2
                with:
                    path: src/
                    args: --level=5

    phpstan7:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/cache@v2
                with:
                    path: '**/vendor'
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-
            -   uses: php-actions/composer@v5
                with:
                    args: --prefer-dist
                    php_version: 8.2

            -   name: PHPStan
                uses: php-actions/phpstan@v2
                with:
                    path: src/
                    args: --level=7

    phpstan8:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/cache@v2
                with:
                    path: '**/vendor'
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-
            -   uses: php-actions/composer@v5
                with:
                    args: --prefer-dist
                    php_version: 8.2

            -   name: PHPStan
                uses: php-actions/phpstan@v2
                with:
                    path: src/
                    args: --level=8

    infection:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.2'
                    tools: composer:v2
                    coverage: pcov
            -   uses: actions/cache@v2
                with:
                    path: '**/vendor'
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-
            -   uses: php-actions/composer@v5
                with:
                    args: --prefer-dist
                    php_version: 8.2

            -   name: Infection
                run: |
                    wget -q https://github.com/infection/infection/releases/download/0.20.0/infection.phar
                    wget -q https://github.com/infection/infection/releases/download/0.20.0/infection.phar.asc
                    chmod +x infection.phar
                    ./infection.phar

            -   name: Store infection log
                uses: actions/upload-artifact@v2
                with:
                    path: infection.log
